server:
  port: 8085

spring:
  application:
    name: radarview-notification
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

jwt:
  secret: radarview-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256
