apiVersion: v1
kind: Secret
metadata:
  name: radarview-secrets
  namespace: radarview
type: Opaque
stringData:
  mysql-root-password: devpass-change-in-production
  mysql-track-password: trackpass
  mysql-auth-password: authpass
  jwt-secret: radarview-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256-change-me
  rabbitmq-password: guest
